---
title: "Problem Session 5"
author: "Mirjana Stevanovic"
date: "10/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- data.frame(0:13,c(14,30,36,68,43,43,30,14,10,6,4,1,1,0))
colnames(data) <- c("n","Frequency")

data$total <- data$n*data$Frequency
N <- sum(data$Frequency)
X.bar <- sum(data$total)/N
theoretical <- dpois(0:13,X.bar)*300

#wrangle data to be able to use a histrogram 
observed <- c(rep(0,14), rep(1,30), rep(2,36), rep(3,68), rep(4, 43), 
              rep(5,43), rep(6, 30), rep(7,14), rep(8,10), rep(9, 6), 
              rep(10,4), rep(11,1), rep(12,1),rep(13,0)) 

expected <- c(rep(0,round(theoretical[1])), rep(1,round(theoretical[2])),
              rep(2,round(theoretical[3])), rep(3,round(theoretical[4])), 
              rep(4,round(theoretical[5])), rep(5,round(theoretical[6])), 
              rep(6,round(theoretical[7])), rep(7,round(theoretical[8])),
              rep(8,round(theoretical[9])), rep(9,round(theoretical[10])),
              rep(10,round(theoretical[11])), rep(11,round(theoretical[12])), 
              rep(12,round(theoretical[13])), rep(13,round(theoretical[14])))

par(mfrow=c(1,2))
hist(observed,prob=T,breaks = 0:13)
hist(expected,prob=T,breaks = 0:13)
```

